
DROP TABLE Club
DROP TABLE Players
DROP TABLE ClubAchievements
DROP TABLE SportEquipments
DROP TABLE Transfers
DROP TABLE ClubEmployees
DROP TABLE Facilities
DROP TABLE Managers
DROP TABLE Fans
DROP TABLE PilotClub
DROP TABLE Finance


CREATE TABLE Finance (
FINANCE_STAT int PRIMARY KEY NOT NULL,
FINANC_RECEİVE int DEFAULT(0),
FINANC_DEBT int DEFAULT(0),
EMPLYEE_SALARY int DEFAULT(0) ,
PLYR_SALARY int DEFAULT(0)
)

CREATE TABLE PilotClub (
PILOT_CLUB_ID int PRIMARY KEY NOT NULL,
PC_NAME nvarchar(30),
PC_ADRESS nvarchar(100),
PC_MARKET_VALUE int,
PC_MAIL nvarchar(60),
PC_PHONE_NUMBER nvarchar(25)
)

CREATE TABLE Fans (
FAN_ID int PRIMARY KEY NOT NULL,
FAN_YOF date
)

CREATE TABLE Managers (
MANAGER_ID int PRIMARY KEY NOT NULL,
MANAGER_NAME nvarchar(30) NOT NULL,
MANAGER_SURNAME nvarchar(30) NOT NULL,
MANAGER_PHONE_NUMBER nvarchar(25)
)

CREATE TABLE Facilities (
FACILITY_ID int PRIMARY KEY NOT NULL,
FACILITY_NAME nvarchar(30) NOT NULL,
FACILITY_ADDRESS nvarchar(100) NOT NULL,
FACILITY_PHONE nvarchar(25)
)

CREATE TABLE ClubEmployees (
EMPLOYEE_ID int PRIMARY KEY NOT NULL,
EMPLOYEE_NAME nvarchar(30) NOT NULL,
EMPLOYEE_SURNAME nvarchar(30) NOT NULL,
EMPLOYEE_DEPARTMENT nvarchar(50) NOT NULL,
EMPLOYEE_SALARY int NOT NULL,
)

CREATE TABLE Transfers (
TRANSFER_ID int PRIMARY KEY NOT NULL,
NUMBER_INCOMİNG_PLAYERS int DEFAULT(0),
NUMBER_OUTGOING_PLAYERS int DEFAULT(0),
INCOMING_NAME nvarchar(30),
INCOMING_SURNAME nvarchar(30),
OUTGOING_NAME nvarchar(30),
OUTGOING_SURNAME nvarchar(30)
)

CREATE TABLE SportEquipments (
EQUIPMENT_ID int PRIMARY KEY NOT NULL,
KIT_NUM int DEFAULT(0),
SHORT_NUM int DEFAULT(0),
SOCKS_NUM int DEFAULT(0),
SHOES_NUM int DEFAULT(0),
BALL_NUM int DEFAULT(0),
TOTAL_EQ_NUM int DEFAULT(0)
)



CREATE TABLE ClubAchievements (
NUMBER_TROPHİES int PRIMARY KEY NOT NULL,
NUMBER_LOCAL_CUP int,
NUMBER_INTRNTNL_CUP int
)

CREATE TABLE Players (
PLAYER_ID int PRIMARY KEY NOT NULL,
PLAYER_NAME nvarchar(30) NOT NULL,
PLAYER_SURNAME nvarchar(30)NOT NULL,
PLAYER_DOB date,
PLAYER_POSITION nvarchar(20),
PLAYER_MV int,
PLAYER_NATION nvarchar(30),
PLAYER_MANAGER_NAME nvarchar(60),
PLAYER_SALARY int,
MANAGER_ID int,
CONSTRAINT fk_mng FOREIGN KEY(MANAGER_ID) REFERENCES Managers(MANAGER_ID)
)

CREATE TABLE Club (
CLUB_ID int PRIMARY KEY NOT NULL,
CLUB_NAME nvarchar(30) NOT NULL,
CLUB_DOB date NOT NULL,
CLUB_ADDRESS nvarchar(100),
CLUB_MV int,
CLUB_MAIL nvarchar(60),
NUMBER_PLAYER int NOT NULL,
PLAYER_ID int NOT NULL,
FINANCE_STAT int NOT NULL,
PILOT_CLUB_ID int NOT NULL,
FAN_ID int NOT NULL,
NUMBER_TROPHİES int NOT NULL,
EMPLOYEE_ID int NOT NULL,
TRANSFER_ID int NOT NULL,
EQUIPMENT_ID int NOT NULL,
FACILITY_ID int NOT NULL,



CONSTRAINT fk_fac FOREIGN KEY(FACILITY_ID) REFERENCES Facilities(FACILITY_ID),
CONSTRAINT fk_finance FOREIGN KEY(FINANCE_STAT) REFERENCES Finance(FINANCE_STAT),
CONSTRAINT fk_pilot FOREIGN KEY(PILOT_CLUB_ID) REFERENCES PilotClub(PILOT_CLUB_ID),
CONSTRAINT fk_fan FOREIGN KEY(FAN_ID) REFERENCES Fans(FAN_ID),
CONSTRAINT fk_emp FOREIGN KEY(EMPLOYEE_ID) REFERENCES ClubEmployees(EMPLOYEE_ID),
CONSTRAINT fk_trans FOREIGN KEY(TRANSFER_ID) REFERENCES Transfers(TRANSFER_ID),
CONSTRAINT fk_eq FOREIGN KEY(EQUIPMENT_ID) REFERENCES SportEquipments(EQUIPMENT_ID),
CONSTRAINT fk_ply FOREIGN KEY(PLAYER_ID) REFERENCES Players(PLAYER_ID),
CONSTRAINT fk_trop FOREIGN KEY(NUMBER_TROPHİES) REFERENCES ClubAchievements(NUMBER_TROPHİES)
)


INSERT INTO Club
VALUES ( 1905 , 'GALATASARAY' , '1905-10-01' , 'ALİ SAMİ YEN SPOR KOMPLEKSİ HUZUR MAH. SEYRANTEPE/SARIYER' , 
141000000 , 'galatasaray1905@gmail.com' , 29 , 93 , 125000000 , 1 , 905 , 98 , 234 , 35 , 23 , 34)
 

INSERT INTO ClubAchievements
VALUES ( 98 , 96 , 2)
 

INSERT INTO ClubEmployees
VALUES (234 , 'AHMET' , 'YILMAZ' , 'ADMINISTRATION' , 40000 )

 
INSERT INTO Facilities
VALUES ( 34 , 'Florya Metin Oktay Tesisleri' , 'Şenlikköy, Germeyan Sk. No:106/88, 34153 Bakırköy/İstanbul' , '5078955678')



INSERT INTO Fans
VALUES (905 , '2001-05-19')
 

INSERT INTO Finance
VALUES (125000000 , 35000000 , 25000000 , 1000000 , 23000000)
 

INSERT INTO Managers
VALUES ( 1 , 'MERİÇ' , 'ASLAN' , '5389034587')
 

INSERT INTO PilotClub
VALUES ( 1, 'Niğde Anadolu FK' , 'ŞAHİNALİ MAH.ŞEHİT FARUK EREN CAD.NO:6 MERKEZ NİĞDE' , 200000 , 'nıgdeanadolufk@gmail.com' , '5432345673')
 

INSERT INTO Players
VALUES ( 93 , 'SACHA' , 'BOEY' , '2000-09-13' , 'RIGHT BACK' , 15000000 , 'FRANCE' , 'Meriç' , 1000000 , 1)
 

INSERT INTO SportEquipments
VALUES ( 23 , 307 , 307 , 614 , 250 , 50 , 2300)
 

INSERT INTO Transfers VALUES (35 , 5 , 2 , 'MAURO' , 'ICARDI' , 'OMER' , 'BAYRAM')


SELECT FINANCE_STAT FROM Finance 
WHERE EXISTS 
(SELECT FINANC_RECEİVE FROM Finance WHERE FINANC_RECEİVE > FINANC_DEBT)
 

SELECT FINANCE_STAT, SUM(EMPLYEE_SALARY + PLYR_SALARY) AS "Total Salary" 
FROM Finance 
GROUP BY FINANCE_STAT 
HAVING SUM(EMPLYEE_SALARY + PLYR_SALARY) > 100000
 

SELECT FINANCE_STAT 
FROM Finance 
UNION SELECT FINANC_RECEİVE FROM Finance
 

SELECT PLAYER_NAME, PLAYER_MV FROM Players ORDER BY PLAYER_MV DESC
 

SELECT PLAYER_NAME FROM Players WHERE EXISTS (SELECT PLAYER_MANAGER_NAME FROM Players WHERE PLAYER_MANAGER_NAME='Meriç')
 

SELECT PLAYER_MANAGER_NAME, SUM(PLAYER_MV) AS "Total Market Value" FROM Players 
GROUP BY PLAYER_MANAGER_NAME HAVING SUM(PLAYER_MV) > 10000000
 

SELECT INCOMING_NAME, INCOMING_SURNAME FROM Transfers 
ORDER BY INCOMING_NAME 
 
SELECT INCOMING_NAME FROM Transfers 
WHERE INCOMING_SURNAME IN 
(SELECT DISTINCT INCOMING_SURNAME FROM Transfers WHERE NUMBER_INCOMİNG_PLAYERS > NUMBER_OUTGOING_PLAYERS)
 

SELECT PC_NAME, PC_MARKET_VALUE 
FROM PilotClub 
WHERE PC_MARKET_VALUE > 100000
 

SELECT PC_NAME,PC_MAIL FROM PilotClub
 

SELECT MANAGER_NAME, MANAGER_SURNAME FROM Managers 
WHERE MANAGER_NAME LIKE 'M%'
 

SELECT FACILITY_NAME FROM Facilities 
UNION SELECT FACILITY_PHONE FROM Facilities
 

SELECT FACILITY_ADDRESS, COUNT(FACILITY_ID) FROM Facilities 
GROUP BY FACILITY_ADDRESS
 

SELECT EMPLOYEE_NAME, EMPLOYEE_SALARY 
FROM ClubEmployees 
WHERE EMPLOYEE_SALARY > 30000
 

SELECT EMPLOYEE_NAME, EMPLOYEE_SALARY FROM ClubEmployees ORDER BY EMPLOYEE_SALARY DESC
 
SELECT DISTINCT EMPLOYEE_NAME FROM ClubEmployees UNION SELECT DISTINCT EMPLOYEE_SURNAME FROM ClubEmployees
 

SELECT Players.PLAYER_NAME, Managers.MANAGER_NAME FROM Players INNER JOIN Managers ON Players.MANAGER_ID = Managers.MANAGER_ID
 

SELECT Players.PLAYER_NAME, Managers.MANAGER_NAME, Managers.MANAGER_PHONE_NUMBER FROM Players 
LEFT JOIN Managers ON Players.MANAGER_ID = Managers.MANAGER_ID WHERE Players.PLAYER_POSITION = 'RIGHT BACK'
 
SELECT Players.PLAYER_NAME, Managers.MANAGER_NAME, Players.PLAYER_MV, Managers.MANAGER_PHONE_NUMBER FROM Players 
INNER JOIN Managers ON Players.MANAGER_ID = Managers.MANAGER_ID ORDER BY Players.PLAYER_MV DESC
 

SELECT Club.CLUB_NAME, Transfers.INCOMING_NAME FROM Club LEFT JOIN Transfers ON Club.TRANSFER_ID = Transfers.TRANSFER_ID
 

SELECT Club.NUMBER_PLAYER, Transfers.NUMBER_INCOMİNG_PLAYERS FROM Club 
LEFT JOIN Transfers ON Club.TRANSFER_ID = Transfers.TRANSFER_ID
 

SELECT CLUB_ID, OUTGOING_NAME, OUTGOING_SURNAME FROM Club 
LEFT JOIN Transfers ON Club.TRANSFER_ID = Transfers.TRANSFER_ID
 

SELECT CLUB_NAME, INCOMING_NAME, INCOMING_SURNAME FROM Club 
LEFT JOIN Transfers ON Club.TRANSFER_ID = Transfers.TRANSFER_ID
 


SELECT Club.CLUB_NAME, ClubEmployees.EMPLOYEE_NAME FROM Club 
LEFT JOIN ClubEmployees ON Club.EMPLOYEE_ID = ClubEmployees.EMPLOYEE_ID
 

SELECT Club.CLUB_DOB, ClubEmployees.EMPLOYEE_SURNAME FROM Club 
INNER JOIN ClubEmployees ON Club.EMPLOYEE_ID = ClubEmployees.EMPLOYEE_ID
 

SELECT Club.CLUB_ADDRESS, ClubEmployees.EMPLOYEE_NAME, ClubEmployees.EMPLOYEE_SURNAME FROM Club 
INNER JOIN ClubEmployees ON Club.EMPLOYEE_ID = ClubEmployees.EMPLOYEE_ID
 


SELECT Club_NAME, FINANCE_STAT, PC_NAME FROM Club 
INNER JOIN PilotClub ON Club.PILOT_CLUB_ID = PilotClub.PILOT_CLUB_ID
 


SELECT CLUB_ID, NUMBER_PLAYER, PC_PHONE_NUMBER FROM Club 
LEFT JOIN PilotClub ON Club.PILOT_CLUB_ID = PilotClub.PILOT_CLUB_ID

 

SELECT CLUB_NAME, PC_MARKET_VALUE, PC_MAIL FROM Club 
INNER JOIN PilotClub ON Club.PILOT_CLUB_ID = PilotClub.PILOT_CLUB_ID
 

SELECT Club_ID, PC_ADRESS FROM Club 
LEFT JOIN PilotClub ON Club.PILOT_CLUB_ID = PilotClub.PILOT_CLUB_ID
 

SELECT Club_NAME, PC_NAME FROM Club 
INNER JOIN PilotClub ON Club.PILOT_CLUB_ID = PilotClub.PILOT_CLUB_ID


CREATE VIEW Club_Summary 
AS SELECT CLUB_ID, CLUB_NAME, NUMBER_PLAYER, NUMBER_TROPHiES FROM Club

 

CREATE VIEW Club_Finance
AS SELECT CLUB_NAME, FINANCE_STAT, CLUB_MV FROM Club

 

CREATE VIEW Club_Contact 
AS SELECT CLUB_NAME, CLUB_ADDRESS, CLUB_MAIL FROM Club

 
CREATE VIEW Club_Players 
AS SELECT CLUB_NAME, PLAYER_ID FROM Club

 
CREATE VIEW Club_Pilots 
AS SELECT CLUB_NAME, PILOT_CLUB_ID FROM Club

 CREATE VIEW Club_Employees 
AS SELECT CLUB_NAME, EMPLOYEE_ID FROM Club

 
CREATE VIEW Club_Transfers 
AS SELECT CLUB_NAME, TRANSFER_ID FROM Club

 CREATE VIEW Club_Equipment 
AS SELECT CLUB_NAME, EQUIPMENT_ID FROM Club

 CREATE VIEW Club_Facilities 
AS SELECT CLUB_NAME, FACILITY_ID FROM Club

 CREATE VIEW Club_DOB
AS SELECT CLUB_NAME, CLUB_DOB FROM Club


UPDATE Club SET CLUB_MV= 168000000

UPDATE PilotClub SET PC_MARKET_VALUE= 284000

UPDATE ClubAchievements SET NUMBER_TROPHİES= 99

UPDATE ClubEmployees SET EMPLOYEE_SALARY= 50000

UPDATE Facilities SET FACILITY_PHONE= '5394543739'



DELETE FROM Club WHERE CLUB_NAME = 'Galatasaray'

DELETE FROM Facilities WHERE FACILITY_ID = 34

DELETE FROM Managers WHERE MANAGER_NAME LIKE 'M%'

DELETE FROM PilotClub WHERE PC_MARKET_VALUE < 300000

DELETE FROM ClubEmployees WHERE EMPLOYEE_DEPARTMENT = 'Doctor'

 



 




 



